defaults:
  - train: default
  - pipe: default
  - dataset:
#      - 360_garden
#      - madoka
#      - 360_bicycle
      - tank_family

project: depth-guide-gs-v2
name: Depth + Normal [360 Bicycle][10000, 0.02, 0.03][depth confidence 0.85][normal confidence 0.80]

ip: 127.0.0.1
port: 6009